### ISSUE TITLE
Need to escape curly braces for search to work

### ISSUE THREAD

**Issue by ukiller** [SteinHQ/Stein#1]
when using the search command I cannot use {} as documented but have to use %7b and %7d. Otherwise the JSON parser raises an error for the colon.

This works:
curl -v 'https://api.steinhq.com/v1/storages/..../Tabellenblatt1?search=%7b"Alter":"13"%7d'

This doesn't:
curl -v 'https://api.steinhq.com/v1/storages/..../Tabellenblatt1?search={"Alter":"13"}'
instead it shows: {"error":"Unexpected token : in JSON at position 7"}

BTW: I use the German version of Google Sheets. Instead of Sheet1 I have to use the localized  Tabellenblatt1. I guess it's the same for other non English versions as well.

**Comment by shivensinha4** [comment]
I'm sorry I didn't spot it earlier. As for encoding the URLs, I believe it's a necessary step as braces are included in the list of unsafe characters. And all unsafe characters must always be encoded within a URL.

Surprisingly enough, even Postman didn't throw an error, even though it is supposed to not encode URLs unless explicitly told to. I'll make sure to mention this in the documentation.
