### ISSUE TITLE
FEATURE: Data column casting type

### ISSUE THREAD

**Issue by ans-4175** [SteinHQ/Stein#4]
All data returned from Stein in type of Text/String.
Need a casting type to recognize: INT, FLOAT, DATE, DATETIME, TIMESTAMP
How do it should handle this?

Btw, how Stein actually works with Mongo<->Sheets interact?

**Comment by shivensinha4** [comment]
@ans-4175 Thanks for the suggestion! Supporting different data types is near the top of the feature list I'm planning to implement, and the next release is expected to include this.

MongoDB is used to store internal data that helps Stein interact with the Sheets API as mentioned in the [README](https://github.com/SteinHQ/Stein#built-with). This includes OAuth keys, list of APIs created, admin user credentials, etc. You can find the exact fields in the schemas defined in the [`models` folder](https://github.com/SteinHQ/Stein/tree/master/models)

Caching and timeouts is something I'm planning to implement, so some data regarding that is expected to be included in the future. Though, that needs a lot of development work and is not the top priority currently.

**Comment by ans-4175** [comment]
I will try and gladly help if it's on the issue list :)

**Comment by shivensinha4** [comment]
Sorry for the late reply.

Thanks for looking into contributing to the repo! It is definitely on the issue list, and it'll be great if you could fix it. The immediate approach that I can think of is that the `valueRenderOption` can be set to `UNFORMATTED_VALUE` (more details [here](https://developers.google.com/sheets/api/reference/rest/v4/spreadsheets.values/get)). But it'll have several effects, like the dates will be converted to a date serial value. I'm not questioning the standards, but we'll have to test how these changes work with the rest of the functions.

How does the search perform after that? Do we also add a new data-aware function to add rows?

We can take steps towards that. At the moment, we can look into creating an option where you can mention if you want data-aware reads. Look into implementing that, and see how that plays with the rest of the system (like search). We can then move onto extending this functionality to write operations if all works out.

Cheers!

**Comment by ans-4175** [comment]
Alright @shivensinha4 I'll try to evaluate your implementation on
https://github.com/SteinHQ/Stein/blob/master/controllers/retrieveSheet.js#L21

Actually at first I am thinking whether on `readSheet.js` or `retrieveSheet.js` I will cast value based on regex checking, especially for date format. But will check onto SheetsAPI.

If we took into account with Search, I believe it's better to put it affecting into
https://github.com/SteinHQ/Stein/blob/master/controllers/retrieveSheet.js

Hmm, add rows data-aware, I haven't thought much about it.

**Comment by shivensinha4** [comment]
I believe adding an option to `retrieveSheet` will be a better, since it powers all read related operations. So the functions we are looking to change will take an additional optional argument which they'll forward to `retrieveSheet`.

But if you implement it with regex, it'll not be guaranteed to reflect the data type as originally in the Sheet. What if there's a date stored as a string? Or more commonly, an integer stored as a string? Implicitly converting them will cause frustrations for the user. I suggest checking the Sheets API, specifically the option I mentioned.

Let me know what you plan on doing. Cheers!

**Comment by shivensinha4** [comment]
Due to inactivity, I'm closing the issue for now. Anyone who wants to pick up the implementation work can let me know here.
