### ISSUE TITLE
FEATURE: Admin Dashboard

### ISSUE THREAD

**Issue by ans-4175** [SteinHQ/Stein#5]
I have tried Stein using Google OAuth.
First we still need to login using email & password then login by google.
Can we just login by using Google OAuth if it's enabled?

Second, if we keep this flow as login is there any possibilities we will seeing Admin Dashboard that lists all of storage and users. Maybe not UAC Feature, just Storage Feature.

Or is it already fixed?

**Comment by shivensinha4** [comment]
The current login flow allows multiple Google accounts to be connected, so we're going to stick to that.

Apart from that, we can look into creating a page that displays the connected Google accounts and storages. At the moment you can access the mongo console, switch to `stein` database, and list the storages (`db.storages.find()`) and the users.

If you'd want to work on creating that page, let me know 🙂
