### ISSUE TITLE
Add Sheet REST API

### ISSUE THREAD

**Issue by karneaud** [SteinHQ/Stein#6]
stumbled upon this gem of a project and this is exactly what I need for mobile app project where I wanted to use google sheets as a database( i currently use AppScript). Does/ Can project include adding sheets via REST instead of creating and account via dashboard?

**Comment by shivensinha4** [comment]
Glad you find the project useful!

At the moment, creating APIs from sheets is not possible through the
exposed interface. You need to log in and add it from the dashboard. A few
more people have requested this functionality, and I have it on the list of
things that would be a nice-to-have. However, that's not something I'm
looking to implement at the moment.
