### ISSUE TITLE
Deploy to now.sh

### ISSUE THREAD

**Issue by sdgandhi** [SteinHQ/Stein#7]
If it's doable, it would probably we worth it ($) to port this to a serverless architecture with a hosted mongo instance.

now.sh is a good choice for stability, performance, and price.

**Comment by shivensinha4** [comment]
Stein already had a hosted version available at https://steinhq.com, with the server sponsored by our friends at DigitalOcean. Is there a use case of yours it does not suffice for?
________________________________
