### ISSUE TITLE
Deprecated legacypeople.googleapis.com

### ISSUE THREAD

**Issue by ruben-farma** [SteinHQ/Stein#8]
As I can read in https://developers.google.com/people/legacy , the legacypeople API was deprecated on March 7, 2019.

Actually, when I run the project, I get:

`{"error":"Legacy People API has not been used in project 4xxxxxx3 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/legacypeople.googleapis.com/overview?project=4xxxx3 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."}`

I tried to enable the legacypeople, but the link is not working.

I enabled the (new) People API but I have the same error message.

It's possible to link with the new API?

BR

**Comment by shivensinha4** [comment]
It was an issue with a previous version of the Passport package. I've released an update now, try updating your copy and restarting. Does it fix the error?

**Comment by ruben-farma** [comment]
It's works! Many thanks!
